version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: antigravity_travellingthroughmorocco
    restart: always
    ports:
      - "8089:80"
    volumes:
      - /opt/antigravity/moroccotravelview.com/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
